package dev.teacode.tmusic.ui

import androidx.compose.ui.graphics.ImageBitmap
import dev.teacode.tmusic.auth.GoogleSignInTokenProvider
import dev.teacode.tmusic.data.LastFmAuthTokenStore
import dev.teacode.tmusic.data.LibraryCacheStore
import dev.teacode.tmusic.data.PendingLibraryMutationStore
import dev.teacode.tmusic.data.PendingPlayEventStore
import dev.teacode.tmusic.data.PlaybackStateStore
import dev.teacode.tmusic.data.RemoteAuthRepository
import dev.teacode.tmusic.data.UserPreferencesStore
import dev.teacode.tmusic.domain.Account
import dev.teacode.tmusic.domain.LastFmConnection
import dev.teacode.tmusic.domain.LibraryAlbum
import dev.teacode.tmusic.domain.LibraryArtist
import dev.teacode.tmusic.domain.LibrarySearchResults
import dev.teacode.tmusic.domain.Playlist
import dev.teacode.tmusic.domain.PlayerState
import dev.teacode.tmusic.domain.Track
import kotlinx.coroutines.Job

internal class AuthSessionActionHost(
    private val authRepository: RemoteAuthRepository,
    private val googleSignInTokenProvider: GoogleSignInTokenProvider,
    private val userPreferencesStore: UserPreferencesStore,
    private val libraryCacheStore: LibraryCacheStore,
    private val playbackStateStore: PlaybackStateStore,
    private val pendingPlayEventStore: PendingPlayEventStore,
    private val pendingLibraryMutationStore: PendingLibraryMutationStore,
    private val lastFmAuthTokenStore: LastFmAuthTokenStore,
    private val getLibraryLoadSerial: () -> Int,
    private val setLibraryLoadSerial: (Int) -> Unit,
    private val getLibraryLoadJob: () -> Job?,
    private val setLibraryLoadJob: (Job?) -> Unit,
    private val setAccount: (Account?) -> Unit,
    private val setAccessToken: (String?) -> Unit,
    private val setCanContinueOffline: (Boolean) -> Unit,
    private val setOfflineOnly: (Boolean) -> Unit,
    private val setSyncMode: (SyncMode) -> Unit,
    private val setLibraryLoading: (Boolean) -> Unit,
    private val setLibraryError: (String?) -> Unit,
    private val setLibraryNotice: (String?) -> Unit,
    private val setPlaylists: (List<Playlist>) -> Unit,
    private val setTracks: (List<Track>) -> Unit,
    private val setHomeArtists: (List<LibraryArtist>) -> Unit,
    private val setArtists: (List<LibraryArtist>) -> Unit,
    private val setAlbums: (List<LibraryAlbum>) -> Unit,
    private val setSavedAlbums: (List<LibraryAlbum>) -> Unit,
    private val setRecentAlbums: (List<LibraryAlbum>) -> Unit,
    private val setDatabaseTrackCount: (Int?) -> Unit,
    private val setAlbumsByArtist: (Map<String, List<LibraryAlbum>>) -> Unit,
    private val setAppearsOnByArtist: (Map<String, List<LibraryAlbum>>) -> Unit,
    private val setLooseTracksByArtist: (Map<String, List<Track>>) -> Unit,
    private val setSimilarArtistsByArtist: (Map<String, List<LibraryArtist>>) -> Unit,
    private val resetLibraryPaging: () -> Unit,
    private val setRecentAlbumsPaging: (RecentAlbumsPagingState) -> Unit,
    private val setAlbumTrackHasMoreById: (Map<String, Boolean>) -> Unit,
    private val setPlaylistTrackHasMoreById: (Map<String, Boolean>) -> Unit,
    private val setAlbumTracksById: (Map<String, List<Track>>) -> Unit,
    private val setSearchResults: (LibrarySearchResults) -> Unit,
    private val setPlayerState: (PlayerState) -> Unit,
    private val setPlaybackQueue: (PlaybackQueue) -> Unit,
    private val clearGaplessPlaybackState: () -> Unit,
    private val clearCrossfadeState: () -> Unit,
    private val setActivePlayEvent: (ActivePlayEvent?) -> Unit,
    private val setPendingPlayEventCount: (Int) -> Unit,
    private val setPendingPlayEventSyncProgress: (Pair<Int, Int>?) -> Unit,
    private val setPendingLibraryMutationCount: (Int) -> Unit,
    private val setPendingLastFmToken: (String?) -> Unit,
    private val setWaitingForLastFmSession: (Boolean) -> Unit,
    private val setLastFmConnection: (LastFmConnection) -> Unit,
    private val setScrobblingPaused: (Boolean) -> Unit,
    private val setShuffleEnabled: (Boolean) -> Unit,
    private val setRepeatMode: (PlaybackRepeatMode) -> Unit,
    private val setProfileAvatarBitmap: (ImageBitmap?) -> Unit,
    private val setProfileAvatarLoadKey: (String?) -> Unit,
    private val setPrefetchedPlaybackUrls: (Map<String, String>) -> Unit,
    private val setPlaybackUrlPrefetchesInProgress: (Set<String>) -> Unit,
    private val setTrackForPlaylistAdd: (Track?) -> Unit,
    private val setPlaylistPickerPlaylists: (List<Playlist>) -> Unit,
    private val setPlaylistPickerLoading: (Boolean) -> Unit,
    private val setPlaylistMetadataLoaded: (Boolean) -> Unit,
    private val setDuplicatePlaylistForAdd: (Playlist?) -> Unit,
    private val setPlaylistAddInProgress: (Boolean) -> Unit,
    private val setFullPlayerOpen: (Boolean) -> Unit,
    private val setQueueOpen: (Boolean) -> Unit,
    private val setDestination: (AppDestination) -> Unit,
    private val setBackStack: (List<AppDestination>) -> Unit,
    private val setAuthError: (String?) -> Unit,
) {
    suspend fun signOutLocalSession(message: String? = null) {
        signOutLocalSessionAction(
            message = message,
            authRepository = authRepository,
            googleSignInTokenProvider = googleSignInTokenProvider,
            userPreferencesStore = userPreferencesStore,
            libraryCacheStore = libraryCacheStore,
            playbackStateStore = playbackStateStore,
            pendingPlayEventStore = pendingPlayEventStore,
            pendingLibraryMutationStore = pendingLibraryMutationStore,
            lastFmAuthTokenStore = lastFmAuthTokenStore,
            getLibraryLoadSerial = getLibraryLoadSerial,
            setLibraryLoadSerial = setLibraryLoadSerial,
            getLibraryLoadJob = getLibraryLoadJob,
            setLibraryLoadJob = setLibraryLoadJob,
            setAccount = setAccount,
            setAccessToken = setAccessToken,
            setCanContinueOffline = setCanContinueOffline,
            setOfflineOnly = setOfflineOnly,
            setSyncMode = setSyncMode,
            setLibraryLoading = setLibraryLoading,
            setLibraryError = setLibraryError,
            setLibraryNotice = setLibraryNotice,
            setPlaylists = setPlaylists,
            setTracks = setTracks,
            setHomeArtists = setHomeArtists,
            setArtists = setArtists,
            setAlbums = setAlbums,
            setSavedAlbums = setSavedAlbums,
            setRecentAlbums = setRecentAlbums,
            setDatabaseTrackCount = setDatabaseTrackCount,
            setAlbumsByArtist = setAlbumsByArtist,
            setAppearsOnByArtist = setAppearsOnByArtist,
            setLooseTracksByArtist = setLooseTracksByArtist,
            setSimilarArtistsByArtist = setSimilarArtistsByArtist,
            resetLibraryPaging = resetLibraryPaging,
            setRecentAlbumsPaging = setRecentAlbumsPaging,
            setAlbumTrackHasMoreById = setAlbumTrackHasMoreById,
            setPlaylistTrackHasMoreById = setPlaylistTrackHasMoreById,
            setAlbumTracksById = setAlbumTracksById,
            setSearchResults = setSearchResults,
            setPlayerState = setPlayerState,
            setPlaybackQueue = setPlaybackQueue,
            clearGaplessPlaybackState = clearGaplessPlaybackState,
            clearCrossfadeState = clearCrossfadeState,
            setActivePlayEvent = setActivePlayEvent,
            setPendingPlayEventCount = setPendingPlayEventCount,
            setPendingPlayEventSyncProgress = setPendingPlayEventSyncProgress,
            setPendingLibraryMutationCount = setPendingLibraryMutationCount,
            setPendingLastFmToken = setPendingLastFmToken,
            setWaitingForLastFmSession = setWaitingForLastFmSession,
            setLastFmConnection = setLastFmConnection,
            setScrobblingPaused = setScrobblingPaused,
            setShuffleEnabled = setShuffleEnabled,
            setRepeatMode = setRepeatMode,
            setProfileAvatarBitmap = setProfileAvatarBitmap,
            setProfileAvatarLoadKey = setProfileAvatarLoadKey,
            setPrefetchedPlaybackUrls = setPrefetchedPlaybackUrls,
            setPlaybackUrlPrefetchesInProgress = setPlaybackUrlPrefetchesInProgress,
            setTrackForPlaylistAdd = setTrackForPlaylistAdd,
            setPlaylistPickerPlaylists = setPlaylistPickerPlaylists,
            setPlaylistPickerLoading = setPlaylistPickerLoading,
            setPlaylistMetadataLoaded = setPlaylistMetadataLoaded,
            setDuplicatePlaylistForAdd = setDuplicatePlaylistForAdd,
            setPlaylistAddInProgress = setPlaylistAddInProgress,
            setFullPlayerOpen = setFullPlayerOpen,
            setQueueOpen = setQueueOpen,
            setDestination = setDestination,
            setBackStack = setBackStack,
            setAuthError = setAuthError,
        )
    }
}
