package dev.teacode.tmusic.ui

import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.ImageBitmap
import dev.teacode.tmusic.BuildConfig
import dev.teacode.tmusic.data.WebLoginCode
import dev.teacode.tmusic.domain.Account
import dev.teacode.tmusic.domain.ArtistSortOption
import dev.teacode.tmusic.domain.LastFmConnection
import dev.teacode.tmusic.domain.LibraryAlbum
import dev.teacode.tmusic.domain.LibraryArtist
import dev.teacode.tmusic.domain.LibrarySearchResults
import dev.teacode.tmusic.domain.PlayerState
import dev.teacode.tmusic.domain.Playlist
import dev.teacode.tmusic.domain.RecentLibraryItem
import dev.teacode.tmusic.domain.Track
import dev.teacode.tmusic.domain.TrackLyrics

internal class TMusicAppRenderState(
    val account: Account?,
    val signingIn: Boolean,
    val authError: String?,
    val useLocalBackend: Boolean,
    val canContinueOffline: Boolean,
    val destination: AppDestination,
    val playlists: List<Playlist>,
    val tracks: List<Track>,
    val recentAlbums: List<LibraryAlbum>,
    val databaseTrackCount: Int?,
    val homeArtists: List<LibraryArtist>,
    val offlineAlbumIds: Set<String>,
    val offlinePlayableTrackIds: Set<String>,
    val artistSortOption: ArtistSortOption,
    val artistServerSortOption: ArtistSortOption?,
    val artists: List<LibraryArtist>,
    val albums: List<LibraryAlbum>,
    val savedAlbums: List<LibraryAlbum>,
    val albumsByArtist: Map<String, List<LibraryAlbum>>,
    val appearsOnByArtist: Map<String, List<LibraryAlbum>>,
    val looseTracksByArtist: Map<String, List<Track>>,
    val similarArtistsByArtist: Map<String, List<LibraryArtist>>,
    val artistAlbumLoadsInProgress: Set<String>,
    val similarArtistLoadsInProgress: Set<String>,
    val albumTrackLoadsInProgress: Set<String>,
    val playlistTrackLoadsInProgress: Set<String>,
    val activePlaylistDownloadIds: Set<String>,
    val activeAlbumDownloadIds: Set<String>,
    val libraryPaging: LibraryPagingState,
    val recentAlbumsPaging: RecentAlbumsPagingState,
    val albumTrackHasMoreById: Map<String, Boolean>,
    val playlistTrackHasMoreById: Map<String, Boolean>,
    val albumTracksById: Map<String, List<Track>>,
    val searchQuery: String,
    val searchFocusRequestSerial: Int,
    val searchResults: LibrarySearchResults,
    val searchLoading: Boolean,
    val searchHasMore: Boolean,
    val recentItems: List<RecentLibraryItem>,
    val playerState: PlayerState,
    val playbackBufferedFraction: Float,
    val playerError: String?,
    val fullPlayerOpen: Boolean,
    val queueOpen: Boolean,
    val artworkBitmaps: Map<String, ImageBitmap>,
    val profileAvatarBitmap: ImageBitmap?,
    val playbackQueue: PlaybackQueue,
    val playbackQueueGeneration: Long,
    val shuffleEnabled: Boolean,
    val repeatMode: PlaybackRepeatMode,
    val libraryLoading: Boolean,
    val libraryError: String?,
    val libraryNotice: String?,
    val canUseServerRequests: Boolean,
    val syncMode: SyncMode,
    val lastFmConnection: LastFmConnection,
    val pendingPlayEventCount: Int,
    val pendingPlayEventSyncProgress: Pair<Int, Int>?,
    val waitingForLastFmSession: Boolean,
    val scrobblingPaused: Boolean,
    val showOnlyActiveSyncedLyrics: Boolean,
    val centerSyncedLyrics: Boolean,
    val animatedPlayerBackground: Boolean,
    val lyricsByTrackId: Map<String, TrackLyrics>,
    val lyricsUnavailableIds: Set<String>,
    val lyricsLoadsInProgress: Set<String>,
    val crossfadeSeconds: Int,
    val equalizerAvailable: Boolean,
    val offlineOnly: Boolean,
    val downloadUsingCellular: Boolean,
    val downloadedSizeBytes: Long,
    val cacheSizeBytes: Long,
    val appUpdateController: AppUpdateController,
    val trackForPlaylistAdd: Track?,
    val playlistPickerPlaylists: List<Playlist>,
    val playlistPickerLoading: Boolean,
    val playlistAddInProgress: Boolean,
    val duplicatePlaylistForAdd: Playlist?,
    val artistChoices: List<LibraryArtist>,
)

internal class TMusicAppRenderActions(
    val onUseLocalBackendChange: (Boolean) -> Unit,
    val onGoogleSignIn: () -> Unit,
    val onContinueOffline: () -> Unit,
    val onRetry: () -> Unit,
    val onRefreshCurrentPlaylist: () -> Unit,
    val onRefreshArtist: (LibraryArtist) -> Unit,
    val onRefreshAlbum: (LibraryAlbum) -> Unit,
    val onLoadMoreArtists: () -> Unit,
    val onArtistSortChange: (ArtistSortOption) -> Unit,
    val onLoadMoreAlbums: () -> Unit,
    val onLoadMoreRecentAlbums: () -> Unit,
    val onLoadMoreAlbumTracks: (LibraryAlbum) -> Unit,
    val onLoadMorePlaylistTracks: (Playlist) -> Unit,
    val onOfflineOnlyChange: (Boolean) -> Unit,
    val onScrobblingPausedChange: (Boolean) -> Unit,
    val onShowOnlyActiveSyncedLyricsChange: (Boolean) -> Unit,
    val onCenterSyncedLyricsChange: (Boolean) -> Unit,
    val onAnimatedPlayerBackgroundChange: (Boolean) -> Unit,
    val onCrossfadeSecondsChange: (Int) -> Unit,
    val onDownloadUsingCellularChange: (Boolean) -> Unit,
    val onOpenEqualizer: () -> Unit,
    val onCreatePlaylist: (String) -> Unit,
    val onUpdatePlaylist: (Playlist, String) -> Unit,
    val onDeletePlaylist: (Playlist) -> Unit,
    val onAddTrackToPlaylistClick: (Track) -> Unit,
    val onDownloadPlaylist: (Playlist) -> Unit,
    val onDeletePlaylistDownload: (Playlist) -> Unit,
    val onPlayPlaylist: (Playlist, List<Track>) -> Unit,
    val onShufflePlayPlaylist: (Playlist, List<Track>) -> Unit,
    val onPlayPlaylistTrack: (Playlist, List<Track>, Int) -> Unit,
    val onRemoveTrackFromPlaylist: (Playlist, String, String) -> Unit,
    val onReorderPlaylistTracks: (Playlist, List<String>) -> Unit,
    val onRequestArtwork: (String, ArtworkImageSize) -> Unit,
    val onConnectLastFm: () -> Unit,
    val onCompleteLastFmSession: () -> Unit,
    val onDisconnectLastFm: () -> Unit,
    val onSyncLastFmUpdates: () -> Unit,
    val onCreateWebLoginCode: suspend () -> WebLoginCode,
    val onClearDownloads: () -> Unit,
    val onClearCache: () -> Unit,
    val onCheckUpdates: () -> Unit,
    val onSelectTab: (AppTab) -> Unit,
    val onSelectPlaylist: (Playlist) -> Unit,
    val onShowAllArtists: () -> Unit,
    val onSelectArtist: (LibraryArtist) -> Unit,
    val onSelectAlbum: (LibraryAlbum) -> Unit,
    val onPlayAlbum: (LibraryAlbum, List<Track>) -> Unit,
    val onPlayAlbumTrack: (LibraryAlbum, List<Track>, Track) -> Unit,
    val onToggleAlbumInLibrary: (LibraryAlbum) -> Unit,
    val onDownloadAlbum: (LibraryAlbum, List<Track>) -> Unit,
    val onDeleteAlbumDownload: (LibraryAlbum, List<Track>) -> Unit,
    val onGoToAlbumArtist: (LibraryAlbum) -> Unit,
    val onBack: () -> Unit,
    val onSelectTrack: (Track) -> Unit,
    val onSearchQueryChange: (String) -> Unit,
    val onLoadMoreSearchTracks: () -> Unit,
    val onClearRecentItems: () -> Unit,
    val onRecentItemClick: (RecentLibraryItem) -> Unit,
    val onSelectSearchArtist: (LibraryArtist) -> Unit,
    val onSelectSearchAlbum: (LibraryAlbum) -> Unit,
    val onSelectSearchTrack: (Track, String) -> Unit,
    val onOpenFullPlayer: () -> Unit,
    val onCloseFullPlayer: () -> Unit,
    val onOpenQueue: () -> Unit,
    val onCloseQueue: () -> Unit,
    val onSelectQueueTrack: (Int) -> Unit,
    val onRemoveQueueTrack: (Int) -> Unit,
    val onReorderQueueTracks: (List<Int>) -> Unit,
    val onAddCurrentTrackToPlaylist: () -> Unit,
    val onAddTrackToQueue: (Track) -> Unit,
    val onGoToTrackArtist: (Track) -> Unit,
    val onGoToTrackAlbum: (Track) -> Unit,
    val onToggleCurrentFavorite: () -> Unit,
    val onToggleTrackFavorite: (Track) -> Unit,
    val onSkipPrevious: () -> Unit,
    val onSkipNext: () -> Unit,
    val onSwipePreviousTrack: () -> Unit,
    val onShuffleChange: (Boolean) -> Unit,
    val onRepeatModeChange: (PlaybackRepeatMode) -> Unit,
    val onTogglePlayback: () -> Unit,
    val onSeek: (Int) -> Unit,
    val onRefreshCurrentLyrics: () -> Unit,
    val onSignOut: () -> Unit,
    val onDismissAddToPlaylist: () -> Unit,
    val onSelectPlaylistForTrack: (Playlist, Track) -> Unit,
    val onConfirmDuplicatePlaylist: (Playlist, Track) -> Unit,
    val onDismissDuplicatePlaylist: () -> Unit,
    val onDismissArtistChoices: () -> Unit,
    val onSelectArtistChoice: (LibraryArtist) -> Unit,
)

@Composable
internal fun TMusicAppRender(
    state: TMusicAppRenderState,
    actions: TMusicAppRenderActions,
) {
    TMusicAppRender(
        account = state.account,
        signingIn = state.signingIn,
        authError = state.authError,
        useLocalBackend = state.useLocalBackend,
        canContinueOffline = state.canContinueOffline,
        destination = state.destination,
        playlists = state.playlists,
        tracks = state.tracks,
        recentAlbums = state.recentAlbums,
        databaseTrackCount = state.databaseTrackCount,
        homeArtists = state.homeArtists,
        offlineAlbumIds = state.offlineAlbumIds,
        offlinePlayableTrackIds = state.offlinePlayableTrackIds,
        artistSortOption = state.artistSortOption,
        artistServerSortOption = state.artistServerSortOption,
        artists = state.artists,
        albums = state.albums,
        savedAlbums = state.savedAlbums,
        albumsByArtist = state.albumsByArtist,
        appearsOnByArtist = state.appearsOnByArtist,
        looseTracksByArtist = state.looseTracksByArtist,
        similarArtistsByArtist = state.similarArtistsByArtist,
        artistAlbumLoadsInProgress = state.artistAlbumLoadsInProgress,
        similarArtistLoadsInProgress = state.similarArtistLoadsInProgress,
        albumTrackLoadsInProgress = state.albumTrackLoadsInProgress,
        playlistTrackLoadsInProgress = state.playlistTrackLoadsInProgress,
        activePlaylistDownloadIds = state.activePlaylistDownloadIds,
        activeAlbumDownloadIds = state.activeAlbumDownloadIds,
        libraryPaging = state.libraryPaging,
        recentAlbumsPaging = state.recentAlbumsPaging,
        albumTrackHasMoreById = state.albumTrackHasMoreById,
        playlistTrackHasMoreById = state.playlistTrackHasMoreById,
        albumTracksById = state.albumTracksById,
        searchQuery = state.searchQuery,
        searchFocusRequestSerial = state.searchFocusRequestSerial,
        searchResults = state.searchResults,
        searchLoading = state.searchLoading,
        searchHasMore = state.searchHasMore,
        recentItems = state.recentItems,
        playerState = state.playerState,
        playbackBufferedFraction = state.playbackBufferedFraction,
        playerError = state.playerError,
        fullPlayerOpen = state.fullPlayerOpen,
        queueOpen = state.queueOpen,
        artworkBitmaps = state.artworkBitmaps,
        profileAvatarBitmap = state.profileAvatarBitmap,
        playbackQueue = state.playbackQueue,
        playbackQueueGeneration = state.playbackQueueGeneration,
        shuffleEnabled = state.shuffleEnabled,
        repeatMode = state.repeatMode,
        libraryLoading = state.libraryLoading,
        libraryError = state.libraryError,
        libraryNotice = state.libraryNotice,
        canUseServerRequests = state.canUseServerRequests,
        syncMode = state.syncMode,
        lastFmConnection = state.lastFmConnection,
        pendingPlayEventCount = state.pendingPlayEventCount,
        pendingPlayEventSyncProgress = state.pendingPlayEventSyncProgress,
        waitingForLastFmSession = state.waitingForLastFmSession,
        scrobblingPaused = state.scrobblingPaused,
        showOnlyActiveSyncedLyrics = state.showOnlyActiveSyncedLyrics,
        centerSyncedLyrics = state.centerSyncedLyrics,
        animatedPlayerBackground = state.animatedPlayerBackground,
        lyricsByTrackId = state.lyricsByTrackId,
        lyricsUnavailableIds = state.lyricsUnavailableIds,
        lyricsLoadsInProgress = state.lyricsLoadsInProgress,
        crossfadeSeconds = state.crossfadeSeconds,
        equalizerAvailable = state.equalizerAvailable,
        offlineOnly = state.offlineOnly,
        downloadUsingCellular = state.downloadUsingCellular,
        downloadedSizeBytes = state.downloadedSizeBytes,
        cacheSizeBytes = state.cacheSizeBytes,
        appUpdateController = state.appUpdateController,
        trackForPlaylistAdd = state.trackForPlaylistAdd,
        playlistPickerPlaylists = state.playlistPickerPlaylists,
        playlistPickerLoading = state.playlistPickerLoading,
        playlistAddInProgress = state.playlistAddInProgress,
        duplicatePlaylistForAdd = state.duplicatePlaylistForAdd,
        artistChoices = state.artistChoices,
        onUseLocalBackendChange = actions.onUseLocalBackendChange,
        onGoogleSignIn = actions.onGoogleSignIn,
        onContinueOffline = actions.onContinueOffline,
        onRetry = actions.onRetry,
        onRefreshCurrentPlaylist = actions.onRefreshCurrentPlaylist,
        onRefreshArtist = actions.onRefreshArtist,
        onRefreshAlbum = actions.onRefreshAlbum,
        onLoadMoreArtists = actions.onLoadMoreArtists,
        onArtistSortChange = actions.onArtistSortChange,
        onLoadMoreAlbums = actions.onLoadMoreAlbums,
        onLoadMoreRecentAlbums = actions.onLoadMoreRecentAlbums,
        onLoadMoreAlbumTracks = actions.onLoadMoreAlbumTracks,
        onLoadMorePlaylistTracks = actions.onLoadMorePlaylistTracks,
        onOfflineOnlyChange = actions.onOfflineOnlyChange,
        onScrobblingPausedChange = actions.onScrobblingPausedChange,
        onShowOnlyActiveSyncedLyricsChange = actions.onShowOnlyActiveSyncedLyricsChange,
        onCenterSyncedLyricsChange = actions.onCenterSyncedLyricsChange,
        onAnimatedPlayerBackgroundChange = actions.onAnimatedPlayerBackgroundChange,
        onCrossfadeSecondsChange = actions.onCrossfadeSecondsChange,
        onDownloadUsingCellularChange = actions.onDownloadUsingCellularChange,
        onOpenEqualizer = actions.onOpenEqualizer,
        onCreatePlaylist = actions.onCreatePlaylist,
        onUpdatePlaylist = actions.onUpdatePlaylist,
        onDeletePlaylist = actions.onDeletePlaylist,
        onAddTrackToPlaylistClick = actions.onAddTrackToPlaylistClick,
        onDownloadPlaylist = actions.onDownloadPlaylist,
        onDeletePlaylistDownload = actions.onDeletePlaylistDownload,
        onPlayPlaylist = actions.onPlayPlaylist,
        onShufflePlayPlaylist = actions.onShufflePlayPlaylist,
        onPlayPlaylistTrack = actions.onPlayPlaylistTrack,
        onRemoveTrackFromPlaylist = actions.onRemoveTrackFromPlaylist,
        onReorderPlaylistTracks = actions.onReorderPlaylistTracks,
        onRequestArtwork = actions.onRequestArtwork,
        onConnectLastFm = actions.onConnectLastFm,
        onCompleteLastFmSession = actions.onCompleteLastFmSession,
        onDisconnectLastFm = actions.onDisconnectLastFm,
        onSyncLastFmUpdates = actions.onSyncLastFmUpdates,
        onCreateWebLoginCode = actions.onCreateWebLoginCode,
        onClearDownloads = actions.onClearDownloads,
        onClearCache = actions.onClearCache,
        onCheckUpdates = actions.onCheckUpdates,
        onSelectTab = actions.onSelectTab,
        onSelectPlaylist = actions.onSelectPlaylist,
        onShowAllArtists = actions.onShowAllArtists,
        onSelectArtist = actions.onSelectArtist,
        onSelectAlbum = actions.onSelectAlbum,
        onPlayAlbum = actions.onPlayAlbum,
        onPlayAlbumTrack = actions.onPlayAlbumTrack,
        onToggleAlbumInLibrary = actions.onToggleAlbumInLibrary,
        onDownloadAlbum = actions.onDownloadAlbum,
        onDeleteAlbumDownload = actions.onDeleteAlbumDownload,
        onGoToAlbumArtist = actions.onGoToAlbumArtist,
        onBack = actions.onBack,
        onSelectTrack = actions.onSelectTrack,
        onSearchQueryChange = actions.onSearchQueryChange,
        onLoadMoreSearchTracks = actions.onLoadMoreSearchTracks,
        onClearRecentItems = actions.onClearRecentItems,
        onRecentItemClick = actions.onRecentItemClick,
        onSelectSearchArtist = actions.onSelectSearchArtist,
        onSelectSearchAlbum = actions.onSelectSearchAlbum,
        onSelectSearchTrack = actions.onSelectSearchTrack,
        onOpenFullPlayer = actions.onOpenFullPlayer,
        onCloseFullPlayer = actions.onCloseFullPlayer,
        onOpenQueue = actions.onOpenQueue,
        onCloseQueue = actions.onCloseQueue,
        onSelectQueueTrack = actions.onSelectQueueTrack,
        onRemoveQueueTrack = actions.onRemoveQueueTrack,
        onReorderQueueTracks = actions.onReorderQueueTracks,
        onAddCurrentTrackToPlaylist = actions.onAddCurrentTrackToPlaylist,
        onAddTrackToQueue = actions.onAddTrackToQueue,
        onGoToTrackArtist = actions.onGoToTrackArtist,
        onGoToTrackAlbum = actions.onGoToTrackAlbum,
        onToggleCurrentFavorite = actions.onToggleCurrentFavorite,
        onToggleTrackFavorite = actions.onToggleTrackFavorite,
        onSkipPrevious = actions.onSkipPrevious,
        onSkipNext = actions.onSkipNext,
        onSwipePreviousTrack = actions.onSwipePreviousTrack,
        onShuffleChange = actions.onShuffleChange,
        onRepeatModeChange = actions.onRepeatModeChange,
        onTogglePlayback = actions.onTogglePlayback,
        onSeek = actions.onSeek,
        onRefreshCurrentLyrics = actions.onRefreshCurrentLyrics,
        onSignOut = actions.onSignOut,
        onDismissAddToPlaylist = actions.onDismissAddToPlaylist,
        onSelectPlaylistForTrack = actions.onSelectPlaylistForTrack,
        onConfirmDuplicatePlaylist = actions.onConfirmDuplicatePlaylist,
        onDismissDuplicatePlaylist = actions.onDismissDuplicatePlaylist,
        onDismissArtistChoices = actions.onDismissArtistChoices,
        onSelectArtistChoice = actions.onSelectArtistChoice,
    )
}

@Composable
internal fun TMusicAppRender(
    account: Account?,
    signingIn: Boolean,
    authError: String?,
    useLocalBackend: Boolean,
    canContinueOffline: Boolean,
    destination: AppDestination,
    playlists: List<Playlist>,
    tracks: List<Track>,
    recentAlbums: List<LibraryAlbum>,
    databaseTrackCount: Int?,
    homeArtists: List<LibraryArtist>,
    offlineAlbumIds: Set<String>,
    offlinePlayableTrackIds: Set<String>,
    artistSortOption: ArtistSortOption,
    artistServerSortOption: ArtistSortOption?,
    artists: List<LibraryArtist>,
    albums: List<LibraryAlbum>,
    savedAlbums: List<LibraryAlbum>,
    albumsByArtist: Map<String, List<LibraryAlbum>>,
    appearsOnByArtist: Map<String, List<LibraryAlbum>>,
    looseTracksByArtist: Map<String, List<Track>>,
    similarArtistsByArtist: Map<String, List<LibraryArtist>>,
    artistAlbumLoadsInProgress: Set<String>,
    similarArtistLoadsInProgress: Set<String>,
    albumTrackLoadsInProgress: Set<String>,
    playlistTrackLoadsInProgress: Set<String>,
    activePlaylistDownloadIds: Set<String>,
    activeAlbumDownloadIds: Set<String>,
    libraryPaging: LibraryPagingState,
    recentAlbumsPaging: RecentAlbumsPagingState,
    albumTrackHasMoreById: Map<String, Boolean>,
    playlistTrackHasMoreById: Map<String, Boolean>,
    albumTracksById: Map<String, List<Track>>,
    searchQuery: String,
    searchFocusRequestSerial: Int,
    searchResults: LibrarySearchResults,
    searchLoading: Boolean,
    searchHasMore: Boolean,
    recentItems: List<RecentLibraryItem>,
    playerState: PlayerState,
    playbackBufferedFraction: Float,
    playerError: String?,
    fullPlayerOpen: Boolean,
    queueOpen: Boolean,
    artworkBitmaps: Map<String, ImageBitmap>,
    profileAvatarBitmap: ImageBitmap?,
    playbackQueue: PlaybackQueue,
    playbackQueueGeneration: Long,
    shuffleEnabled: Boolean,
    repeatMode: PlaybackRepeatMode,
    libraryLoading: Boolean,
    libraryError: String?,
    libraryNotice: String?,
    canUseServerRequests: Boolean,
    syncMode: SyncMode,
    lastFmConnection: LastFmConnection,
    pendingPlayEventCount: Int,
    pendingPlayEventSyncProgress: Pair<Int, Int>?,
    waitingForLastFmSession: Boolean,
    scrobblingPaused: Boolean,
    showOnlyActiveSyncedLyrics: Boolean,
    centerSyncedLyrics: Boolean,
    animatedPlayerBackground: Boolean,
    lyricsByTrackId: Map<String, TrackLyrics>,
    lyricsUnavailableIds: Set<String>,
    lyricsLoadsInProgress: Set<String>,
    crossfadeSeconds: Int,
    equalizerAvailable: Boolean,
    offlineOnly: Boolean,
    downloadUsingCellular: Boolean,
    downloadedSizeBytes: Long,
    cacheSizeBytes: Long,
    appUpdateController: AppUpdateController,
    trackForPlaylistAdd: Track?,
    playlistPickerPlaylists: List<Playlist>,
    playlistPickerLoading: Boolean,
    playlistAddInProgress: Boolean,
    duplicatePlaylistForAdd: Playlist?,
    artistChoices: List<LibraryArtist>,
    onUseLocalBackendChange: (Boolean) -> Unit,
    onGoogleSignIn: () -> Unit,
    onContinueOffline: () -> Unit,
    onRetry: () -> Unit,
    onRefreshCurrentPlaylist: () -> Unit,
    onRefreshArtist: (LibraryArtist) -> Unit,
    onRefreshAlbum: (LibraryAlbum) -> Unit,
    onLoadMoreArtists: () -> Unit,
    onArtistSortChange: (ArtistSortOption) -> Unit,
    onLoadMoreAlbums: () -> Unit,
    onLoadMoreRecentAlbums: () -> Unit,
    onLoadMoreAlbumTracks: (LibraryAlbum) -> Unit,
    onLoadMorePlaylistTracks: (Playlist) -> Unit,
    onOfflineOnlyChange: (Boolean) -> Unit,
    onScrobblingPausedChange: (Boolean) -> Unit,
    onShowOnlyActiveSyncedLyricsChange: (Boolean) -> Unit,
    onCenterSyncedLyricsChange: (Boolean) -> Unit,
    onAnimatedPlayerBackgroundChange: (Boolean) -> Unit,
    onCrossfadeSecondsChange: (Int) -> Unit,
    onDownloadUsingCellularChange: (Boolean) -> Unit,
    onOpenEqualizer: () -> Unit,
    onCreatePlaylist: (String) -> Unit,
    onUpdatePlaylist: (Playlist, String) -> Unit,
    onDeletePlaylist: (Playlist) -> Unit,
    onAddTrackToPlaylistClick: (Track) -> Unit,
    onDownloadPlaylist: (Playlist) -> Unit,
    onDeletePlaylistDownload: (Playlist) -> Unit,
    onPlayPlaylist: (Playlist, List<Track>) -> Unit,
    onShufflePlayPlaylist: (Playlist, List<Track>) -> Unit,
    onPlayPlaylistTrack: (Playlist, List<Track>, Int) -> Unit,
    onRemoveTrackFromPlaylist: (Playlist, String, String) -> Unit,
    onReorderPlaylistTracks: (Playlist, List<String>) -> Unit,
    onRequestArtwork: (String, ArtworkImageSize) -> Unit,
    onConnectLastFm: () -> Unit,
    onCompleteLastFmSession: () -> Unit,
    onDisconnectLastFm: () -> Unit,
    onSyncLastFmUpdates: () -> Unit,
    onCreateWebLoginCode: suspend () -> WebLoginCode,
    onClearDownloads: () -> Unit,
    onClearCache: () -> Unit,
    onCheckUpdates: () -> Unit,
    onSelectTab: (AppTab) -> Unit,
    onSelectPlaylist: (Playlist) -> Unit,
    onShowAllArtists: () -> Unit,
    onSelectArtist: (LibraryArtist) -> Unit,
    onSelectAlbum: (LibraryAlbum) -> Unit,
    onPlayAlbum: (LibraryAlbum, List<Track>) -> Unit,
    onPlayAlbumTrack: (LibraryAlbum, List<Track>, Track) -> Unit,
    onToggleAlbumInLibrary: (LibraryAlbum) -> Unit,
    onDownloadAlbum: (LibraryAlbum, List<Track>) -> Unit,
    onDeleteAlbumDownload: (LibraryAlbum, List<Track>) -> Unit,
    onGoToAlbumArtist: (LibraryAlbum) -> Unit,
    onBack: () -> Unit,
    onSelectTrack: (Track) -> Unit,
    onSearchQueryChange: (String) -> Unit,
    onLoadMoreSearchTracks: () -> Unit,
    onClearRecentItems: () -> Unit,
    onRecentItemClick: (RecentLibraryItem) -> Unit,
    onSelectSearchArtist: (LibraryArtist) -> Unit,
    onSelectSearchAlbum: (LibraryAlbum) -> Unit,
    onSelectSearchTrack: (Track, String) -> Unit,
    onOpenFullPlayer: () -> Unit,
    onCloseFullPlayer: () -> Unit,
    onOpenQueue: () -> Unit,
    onCloseQueue: () -> Unit,
    onSelectQueueTrack: (Int) -> Unit,
    onRemoveQueueTrack: (Int) -> Unit,
    onReorderQueueTracks: (List<Int>) -> Unit,
    onAddCurrentTrackToPlaylist: () -> Unit,
    onAddTrackToQueue: (Track) -> Unit,
    onGoToTrackArtist: (Track) -> Unit,
    onGoToTrackAlbum: (Track) -> Unit,
    onToggleCurrentFavorite: () -> Unit,
    onToggleTrackFavorite: (Track) -> Unit,
    onSkipPrevious: () -> Unit,
    onSkipNext: () -> Unit,
    onSwipePreviousTrack: () -> Unit,
    onShuffleChange: (Boolean) -> Unit,
    onRepeatModeChange: (PlaybackRepeatMode) -> Unit,
    onTogglePlayback: () -> Unit,
    onSeek: (Int) -> Unit,
    onRefreshCurrentLyrics: () -> Unit,
    onSignOut: () -> Unit,
    onDismissAddToPlaylist: () -> Unit,
    onSelectPlaylistForTrack: (Playlist, Track) -> Unit,
    onConfirmDuplicatePlaylist: (Playlist, Track) -> Unit,
    onDismissDuplicatePlaylist: () -> Unit,
    onDismissArtistChoices: () -> Unit,
    onSelectArtistChoice: (LibraryArtist) -> Unit,
) {
    Surface(
        modifier = Modifier.fillMaxSize(),
        color = MaterialTheme.colorScheme.background,
    ) {
        Box(modifier = Modifier.fillMaxSize()) {
            when {
                account == null -> SignInScreen(
                    isLoading = signingIn,
                    errorMessage = authError,
                    useLocalBackend = useLocalBackend,
                    showLocalBackendOption = BuildConfig.VERSION_NAME.endsWith("-debug"),
                    onUseLocalBackendChange = onUseLocalBackendChange,
                    onGoogleSignIn = onGoogleSignIn,
                    canContinueOffline = canContinueOffline,
                    onContinueOffline = onContinueOffline,
                )

                else -> MainShell(
                    account = account,
                    destination = destination,
                    playlists = playlists,
                    tracks = tracks,
                    recentAlbums = recentAlbums,
                    databaseTrackCount = databaseTrackCount,
                    homeArtists = homeArtists,
                    offlineAlbumIds = offlineAlbumIds,
                    offlinePlayableTrackIds = offlinePlayableTrackIds,
                    artistSortOption = artistSortOption,
                    artistServerSortOption = artistServerSortOption,
                    artists = artists,
                    albums = albums,
                    savedAlbums = savedAlbums,
                    albumsByArtist = albumsByArtist,
                    appearsOnByArtist = appearsOnByArtist,
                    looseTracksByArtist = looseTracksByArtist,
                    similarArtistsByArtist = similarArtistsByArtist,
                    artistAlbumLoadsInProgress = artistAlbumLoadsInProgress,
                    similarArtistLoadsInProgress = similarArtistLoadsInProgress,
                    albumTrackLoadsInProgress = albumTrackLoadsInProgress,
                    playlistTrackLoadsInProgress = playlistTrackLoadsInProgress,
                    activePlaylistDownloadIds = activePlaylistDownloadIds,
                    activeAlbumDownloadIds = activeAlbumDownloadIds,
                    artistListLoadingMore = libraryPaging.artistLoadingMore,
                    albumListLoadingMore = libraryPaging.albumLoadingMore,
                    recentAlbumsLoadingMore = recentAlbumsPaging.loadingMore,
                    artistListHasMore = libraryPaging.artistHasMore,
                    albumListHasMore = libraryPaging.albumHasMore,
                    recentAlbumsHasMore = recentAlbumsPaging.hasMore,
                    albumTrackHasMoreById = albumTrackHasMoreById,
                    playlistTrackHasMoreById = playlistTrackHasMoreById,
                    albumTracksById = albumTracksById,
                    searchQuery = searchQuery,
                    searchFocusRequestSerial = searchFocusRequestSerial,
                    searchResults = searchResults,
                    searchLoading = searchLoading,
                    searchHasMore = searchHasMore,
                    recentItems = recentItems,
                    playerState = playerState,
                    playbackBufferedFraction = if (playerState.currentTrack?.id?.let { it in offlinePlayableTrackIds } == true) {
                        1f
                    } else {
                        playbackBufferedFraction
                    },
                    playerError = playerError,
                    fullPlayerOpen = fullPlayerOpen,
                    queueOpen = queueOpen,
                    artworkBitmap = artworkBitmaps.artworkBitmap(playerState.currentTrack?.listArtworkKey(), ArtworkImageSize.FullPlayer),
                    artworkBitmaps = artworkBitmaps,
                    profileAvatarBitmap = profileAvatarBitmap,
                    canSkipTracks = playbackQueue.canSkip,
                    shuffleEnabled = shuffleEnabled,
                    repeatMode = repeatMode,
                    currentLyrics = playerState.currentTrack?.id?.let(lyricsByTrackId::get),
                    currentLyricsUnavailable = playerState.currentTrack?.id
                        ?.let { it in lyricsUnavailableIds } == true,
                    currentLyricsLoading = playerState.currentTrack?.id
                        ?.let { it in lyricsLoadsInProgress } == true,
                    activePlaylistId = playbackQueue.playlistId,
                    activeAlbumId = playbackQueue.sourceId.takeIf { playbackQueue.sourceType == PlaybackSourceType.Album },
                    queueTracks = playbackQueue.tracks,
                    manualQueueFlags = playbackQueue.normalizedManualQueueFlags(),
                    queueCurrentIndex = playbackQueue.currentIndex,
                    playbackQueueGeneration = playbackQueueGeneration,
                    playerSourceLabel = playerState.currentTrack?.let {
                        when (playbackQueue.sourceType) {
                            PlaybackSourceType.Search -> "PLAYING FROM SEARCH"
                            PlaybackSourceType.Recent -> "PLAYING FROM LATEST TRACKS"
                            PlaybackSourceType.Playlist -> "PLAYING FROM PLAYLIST"
                            PlaybackSourceType.Album -> "PLAYING FROM ALBUM"
                        }
                    },
                    playerSourceDetail = playbackQueue.sourceTitle
                        ?: playbackQueue.playlistId?.let { playlistId ->
                            playlists.firstOrNull { it.id == playlistId }?.title
                        },
                    playerSourceType = playbackQueue.sourceType,
                    isLoading = libraryLoading,
                    errorMessage = libraryError.takeUnless { offlineOnly },
                    noticeMessage = libraryNotice,
                    useLocalBackend = useLocalBackend,
                    showLocalBackendOption = BuildConfig.VERSION_NAME.endsWith("-debug"),
                    canUseServerRequests = canUseServerRequests,
                    syncMode = syncMode,
                    lastFmConnection = lastFmConnection,
                    pendingPlayEventCount = pendingPlayEventCount,
                    pendingPlayEventSyncProgress = pendingPlayEventSyncProgress,
                    waitingForLastFmSession = waitingForLastFmSession,
                    scrobblingPaused = scrobblingPaused,
                    showOnlyActiveSyncedLyrics = showOnlyActiveSyncedLyrics,
                    centerSyncedLyrics = centerSyncedLyrics,
                    animatedPlayerBackground = animatedPlayerBackground,
                    crossfadeSeconds = crossfadeSeconds,
                    equalizerAvailable = equalizerAvailable,
                    offlineOnly = offlineOnly,
                    downloadUsingCellular = downloadUsingCellular,
                    downloadedSizeBytes = downloadedSizeBytes,
                    cacheSizeBytes = cacheSizeBytes,
                    appUpdateController = appUpdateController,
                    appVersionName = BuildConfig.VERSION_NAME,
                    onRetry = onRetry,
                    onRefreshHome = onRetry,
                    onRefreshLibrary = onRetry,
                    onRefreshPlaylist = onRefreshCurrentPlaylist,
                    onRefreshArtist = onRefreshArtist,
                    onRefreshAlbum = onRefreshAlbum,
                    onLoadMoreArtists = onLoadMoreArtists,
                    onArtistSortChange = onArtistSortChange,
                    onLoadMoreAlbums = onLoadMoreAlbums,
                    onLoadMoreRecentAlbums = onLoadMoreRecentAlbums,
                    onLoadMoreAlbumTracks = onLoadMoreAlbumTracks,
                    onLoadMorePlaylistTracks = onLoadMorePlaylistTracks,
                    onUseLocalBackendChange = onUseLocalBackendChange,
                    onOfflineOnlyChange = onOfflineOnlyChange,
                    onScrobblingPausedChange = onScrobblingPausedChange,
                    onShowOnlyActiveSyncedLyricsChange = onShowOnlyActiveSyncedLyricsChange,
                    onCenterSyncedLyricsChange = onCenterSyncedLyricsChange,
                    onAnimatedPlayerBackgroundChange = onAnimatedPlayerBackgroundChange,
                    onCrossfadeSecondsChange = onCrossfadeSecondsChange,
                    onDownloadUsingCellularChange = onDownloadUsingCellularChange,
                    onOpenEqualizer = onOpenEqualizer,
                    onCreatePlaylist = onCreatePlaylist,
                    onUpdatePlaylist = onUpdatePlaylist,
                    onDeletePlaylist = onDeletePlaylist,
                    onAddTrackToPlaylistClick = onAddTrackToPlaylistClick,
                    onDownloadPlaylist = onDownloadPlaylist,
                    onDeletePlaylistDownload = onDeletePlaylistDownload,
                    onPlayPlaylist = onPlayPlaylist,
                    onShufflePlayPlaylist = onShufflePlayPlaylist,
                    onPlayPlaylistTrack = onPlayPlaylistTrack,
                    onRemoveTrackFromPlaylist = onRemoveTrackFromPlaylist,
                    onReorderPlaylistTracks = onReorderPlaylistTracks,
                    onRequestArtwork = onRequestArtwork,
                    onConnectLastFm = onConnectLastFm,
                    onCompleteLastFmSession = onCompleteLastFmSession,
                    onDisconnectLastFm = onDisconnectLastFm,
                    onSyncLastFmUpdates = onSyncLastFmUpdates,
                    onCreateWebLoginCode = onCreateWebLoginCode,
                    onClearDownloads = onClearDownloads,
                    onClearCache = onClearCache,
                    onCheckUpdates = onCheckUpdates,
                    onSelectTab = onSelectTab,
                    onSelectPlaylist = onSelectPlaylist,
                    onShowAllArtists = onShowAllArtists,
                    onSelectArtist = onSelectArtist,
                    onSelectAlbum = onSelectAlbum,
                    onPlayAlbum = onPlayAlbum,
                    onPlayAlbumTrack = onPlayAlbumTrack,
                    onToggleAlbumInLibrary = onToggleAlbumInLibrary,
                    onDownloadAlbum = onDownloadAlbum,
                    onDeleteAlbumDownload = onDeleteAlbumDownload,
                    onGoToAlbumArtist = onGoToAlbumArtist,
                    onBack = onBack,
                    onSelectTrack = onSelectTrack,
                    onSearchQueryChange = onSearchQueryChange,
                    onLoadMoreSearchTracks = onLoadMoreSearchTracks,
                    onClearRecentItems = onClearRecentItems,
                    onRecentItemClick = onRecentItemClick,
                    onSelectSearchArtist = onSelectSearchArtist,
                    onSelectSearchAlbum = onSelectSearchAlbum,
                    onSelectSearchTrack = onSelectSearchTrack,
                    onOpenFullPlayer = onOpenFullPlayer,
                    onCloseFullPlayer = onCloseFullPlayer,
                    onOpenQueue = onOpenQueue,
                    onCloseQueue = onCloseQueue,
                    onSelectQueueTrack = onSelectQueueTrack,
                    onRemoveQueueTrack = onRemoveQueueTrack,
                    onReorderQueueTracks = onReorderQueueTracks,
                    onAddCurrentTrackToPlaylist = onAddCurrentTrackToPlaylist,
                    onAddTrackToQueue = onAddTrackToQueue,
                    onGoToTrackArtist = onGoToTrackArtist,
                    onGoToTrackAlbum = onGoToTrackAlbum,
                    onToggleCurrentFavorite = onToggleCurrentFavorite,
                    onToggleTrackFavorite = onToggleTrackFavorite,
                    onSkipPrevious = onSkipPrevious,
                    onSkipNext = onSkipNext,
                    onSwipePreviousTrack = onSwipePreviousTrack,
                    onShuffleChange = onShuffleChange,
                    onRepeatModeChange = onRepeatModeChange,
                    onTogglePlayback = onTogglePlayback,
                    onSeek = onSeek,
                    onRefreshCurrentLyrics = onRefreshCurrentLyrics,
                    onSignOut = onSignOut,
                )
            }
            TMusicDialogs(
                appUpdateController = appUpdateController,
                trackForPlaylistAdd = trackForPlaylistAdd,
                playlistPickerPlaylists = playlistPickerPlaylists,
                playlistPickerLoading = playlistPickerLoading,
                playlistAddInProgress = playlistAddInProgress,
                duplicatePlaylistForAdd = duplicatePlaylistForAdd,
                artistChoices = artistChoices,
                artworkBitmaps = artworkBitmaps,
                onRequestArtwork = onRequestArtwork,
                onDismissAddToPlaylist = onDismissAddToPlaylist,
                onSelectPlaylistForTrack = onSelectPlaylistForTrack,
                onConfirmDuplicatePlaylist = onConfirmDuplicatePlaylist,
                onDismissDuplicatePlaylist = onDismissDuplicatePlaylist,
                onDismissArtistChoices = onDismissArtistChoices,
                onSelectArtistChoice = onSelectArtistChoice,
            )
        }
    }
}

@Composable
private fun TMusicDialogs(
    appUpdateController: AppUpdateController,
    trackForPlaylistAdd: Track?,
    playlistPickerPlaylists: List<Playlist>,
    playlistPickerLoading: Boolean,
    playlistAddInProgress: Boolean,
    duplicatePlaylistForAdd: Playlist?,
    artistChoices: List<LibraryArtist>,
    artworkBitmaps: Map<String, ImageBitmap>,
    onRequestArtwork: (String, ArtworkImageSize) -> Unit,
    onDismissAddToPlaylist: () -> Unit,
    onSelectPlaylistForTrack: (Playlist, Track) -> Unit,
    onConfirmDuplicatePlaylist: (Playlist, Track) -> Unit,
    onDismissDuplicatePlaylist: () -> Unit,
    onDismissArtistChoices: () -> Unit,
    onSelectArtistChoice: (LibraryArtist) -> Unit,
) {
    AppUpdateDialogHost(appUpdateController)
    trackForPlaylistAdd?.let { track ->
        AddTrackToPlaylistDialog(
            track = track,
            playlists = playlistPickerPlaylists,
            isLoading = playlistPickerLoading || playlistAddInProgress,
            duplicatePlaylist = duplicatePlaylistForAdd,
            onDismiss = onDismissAddToPlaylist,
            onSelectPlaylist = { playlist -> onSelectPlaylistForTrack(playlist, track) },
            onConfirmDuplicate = { playlist -> onConfirmDuplicatePlaylist(playlist, track) },
            onDismissDuplicate = onDismissDuplicatePlaylist,
        )
    }
    if (artistChoices.isNotEmpty()) {
        ArtistChoiceDialog(
            artists = artistChoices,
            artworkBitmaps = artworkBitmaps,
            onRequestArtwork = onRequestArtwork,
            onDismiss = onDismissArtistChoices,
            onSelectArtist = onSelectArtistChoice,
        )
    }
}

@Composable
internal fun TMusicAppRenderBinding(
    state: TMusicAppRenderState,
    actions: TMusicAppRenderActions,
    showEnableCellularDownloadDialog: Boolean,
    onDismissEnableCellularDownloadDialog: () -> Unit,
    onEnableCellularDownload: () -> Unit,
) {
    TMusicAppRender(
        state = state,
        actions = actions,
    )
    EnableCellularDownloadDialog(
        visible = showEnableCellularDownloadDialog,
        onDismiss = onDismissEnableCellularDownloadDialog,
        onEnable = onEnableCellularDownload,
    )
}

@Composable
internal fun TMusicAppRuntimeRenderBinding(
    appState: TMusicAppMutableState,
    offlinePlayableTrackIds: Set<String>,
    appUpdateController: AppUpdateController,
    canUseServerRequests: Boolean,
    equalizerAvailable: Boolean,
    onUseLocalBackendChange: (Boolean) -> Unit,
    onGoogleSignIn: () -> Unit,
    onContinueOffline: () -> Unit,
    loadLibrary: (AppDestination) -> Unit,
    onRefreshCurrentPlaylist: () -> Unit,
    loadArtistAlbums: (LibraryArtist, Boolean) -> Unit,
    loadSimilarArtists: (LibraryArtist, Boolean) -> Unit,
    loadAlbumTracks: (LibraryAlbum, Boolean) -> Unit,
    onLoadMoreArtists: () -> Unit,
    onArtistSortChange: (ArtistSortOption) -> Unit,
    onLoadMoreAlbums: () -> Unit,
    onLoadMoreRecentAlbums: () -> Unit,
    loadFullFavoritesPlaylist: (Playlist) -> Unit,
    loadPlaylistTracks: (Playlist, Boolean) -> Unit,
    onOfflineOnlyChange: (Boolean) -> Unit,
    onScrobblingPausedChange: (Boolean) -> Unit,
    onShowOnlyActiveSyncedLyricsChange: (Boolean) -> Unit,
    onCenterSyncedLyricsChange: (Boolean) -> Unit,
    onAnimatedPlayerBackgroundChange: (Boolean) -> Unit,
    onCrossfadeSecondsChange: (Int) -> Unit,
    onDownloadUsingCellularChange: (Boolean) -> Unit,
    onOpenEqualizer: () -> Unit,
    onCreatePlaylist: (String) -> Unit,
    onUpdatePlaylist: (Playlist, String) -> Unit,
    onDeletePlaylist: (Playlist) -> Unit,
    onAddTrackToPlaylistClick: (Track) -> Unit,
    onDownloadPlaylist: (Playlist) -> Unit,
    onDeletePlaylistDownload: (Playlist) -> Unit,
    onPlayPlaylist: (Playlist, List<Track>) -> Unit,
    onShufflePlayPlaylist: (Playlist, List<Track>) -> Unit,
    onPlayPlaylistTrack: (Playlist, List<Track>, Int) -> Unit,
    onRemoveTrackFromPlaylist: (Playlist, String, String) -> Unit,
    onReorderPlaylistTracks: (Playlist, List<String>) -> Unit,
    onRequestArtwork: (String, ArtworkImageSize) -> Unit,
    onConnectLastFm: () -> Unit,
    onCompleteLastFmSession: () -> Unit,
    onDisconnectLastFm: () -> Unit,
    onSyncLastFmUpdates: () -> Unit,
    onCreateWebLoginCode: suspend () -> WebLoginCode,
    onClearDownloads: () -> Unit,
    onClearCache: () -> Unit,
    onCheckUpdates: () -> Unit,
    onSelectTab: (AppTab) -> Unit,
    onSelectPlaylist: (Playlist) -> Unit,
    onShowAllArtists: () -> Unit,
    onSelectArtist: (LibraryArtist) -> Unit,
    onSelectAlbum: (LibraryAlbum) -> Unit,
    onPlayAlbum: (LibraryAlbum, List<Track>) -> Unit,
    onPlayAlbumTrack: (LibraryAlbum, List<Track>, Track) -> Unit,
    onToggleAlbumInLibrary: (LibraryAlbum) -> Unit,
    onDownloadAlbum: (LibraryAlbum, List<Track>) -> Unit,
    onDeleteAlbumDownload: (LibraryAlbum, List<Track>) -> Unit,
    onGoToAlbumArtist: (LibraryAlbum) -> Unit,
    onBack: () -> Unit,
    onSelectTrack: (Track) -> Unit,
    onClearRecentItems: () -> Unit,
    onRecentItemClick: (RecentLibraryItem) -> Unit,
    onSelectSearchArtist: (LibraryArtist) -> Unit,
    onSelectSearchAlbum: (LibraryAlbum) -> Unit,
    onSelectSearchTrack: (Track, String) -> Unit,
    onOpenFullPlayer: () -> Unit,
    onSelectQueueTrack: (Int) -> Unit,
    onRemoveQueueTrack: (Int) -> Unit,
    onReorderQueueTracks: (List<Int>) -> Unit,
    onAddTrackToQueue: (Track) -> Unit,
    onGoToTrackArtist: (Track) -> Unit,
    onGoToTrackAlbum: (Track) -> Unit,
    onToggleTrackFavorite: (Track) -> Unit,
    onSkipInQueue: (Int, Boolean) -> Unit,
    onShuffleChange: (Boolean) -> Unit,
    onRepeatModeChange: (PlaybackRepeatMode) -> Unit,
    onTogglePlayback: () -> Unit,
    onSeek: (Int) -> Unit,
    onRefreshLyrics: (Track) -> Unit,
    onSignOut: () -> Unit,
    onSelectPlaylistForTrack: (Playlist, Track) -> Unit,
    onConfirmDuplicatePlaylist: (Playlist, Track) -> Unit,
) {
    TMusicAppRenderBinding(
        state = TMusicAppRenderState(
            account = appState.account,
            signingIn = appState.signingIn,
            authError = appState.authError,
            useLocalBackend = appState.useLocalBackend,
            canContinueOffline = appState.canContinueOffline,
            destination = appState.destination,
            playlists = appState.playlists,
            tracks = appState.tracks,
            recentAlbums = appState.recentAlbums,
            databaseTrackCount = appState.databaseTrackCount,
            homeArtists = appState.homeArtists,
            offlineAlbumIds = appState.offlineAlbumIds,
            offlinePlayableTrackIds = offlinePlayableTrackIds,
            artistSortOption = appState.artistSortOption,
            artistServerSortOption = appState.artistServerSortOption,
            artists = appState.artists,
            albums = appState.albums,
            savedAlbums = appState.savedAlbums,
            albumsByArtist = appState.albumsByArtist,
            appearsOnByArtist = appState.appearsOnByArtist,
            looseTracksByArtist = appState.looseTracksByArtist,
            similarArtistsByArtist = appState.similarArtistsByArtist,
            artistAlbumLoadsInProgress = appState.artistAlbumLoadsInProgress,
            similarArtistLoadsInProgress = appState.similarArtistLoadsInProgress,
            albumTrackLoadsInProgress = appState.albumTrackLoadsInProgress,
            playlistTrackLoadsInProgress = appState.playlistTrackLoadsInProgress,
            activePlaylistDownloadIds = appState.playlistDownloadJobs.activeDownloadIds(),
            activeAlbumDownloadIds = appState.albumDownloadJobs.activeDownloadIds(),
            libraryPaging = appState.libraryPaging,
            recentAlbumsPaging = appState.recentAlbumsPaging,
            albumTrackHasMoreById = appState.albumTrackHasMoreById,
            playlistTrackHasMoreById = appState.playlistTrackHasMoreById,
            albumTracksById = appState.albumTracksById,
            searchQuery = appState.searchQuery,
            searchFocusRequestSerial = appState.searchFocusRequestSerial,
            searchResults = appState.searchResults,
            searchLoading = appState.searchLoading,
            searchHasMore = appState.searchHasMore,
            recentItems = appState.recentItems,
            playerState = appState.playerState,
            playbackBufferedFraction = appState.playbackBufferedFraction,
            playerError = appState.playerError,
            fullPlayerOpen = appState.fullPlayerOpen,
            queueOpen = appState.queueOpen,
            artworkBitmaps = appState.artworkBitmaps,
            profileAvatarBitmap = appState.profileAvatarBitmap,
            playbackQueue = appState.playbackQueue,
            playbackQueueGeneration = appState.playbackQueueGeneration,
            shuffleEnabled = appState.shuffleEnabled,
            repeatMode = appState.repeatMode,
            libraryLoading = appState.libraryLoading,
            libraryError = appState.libraryError,
            libraryNotice = appState.libraryNotice,
            canUseServerRequests = canUseServerRequests,
            syncMode = appState.syncMode,
            lastFmConnection = appState.lastFmConnection,
            pendingPlayEventCount = appState.pendingPlayEventCount,
            pendingPlayEventSyncProgress = appState.pendingPlayEventSyncProgress,
            waitingForLastFmSession = appState.waitingForLastFmSession,
            scrobblingPaused = appState.scrobblingPaused,
            showOnlyActiveSyncedLyrics = appState.showOnlyActiveSyncedLyrics,
            centerSyncedLyrics = appState.centerSyncedLyrics,
            animatedPlayerBackground = appState.animatedPlayerBackground,
            lyricsByTrackId = appState.lyricsByTrackId,
            lyricsUnavailableIds = appState.lyricsUnavailableIds,
            lyricsLoadsInProgress = appState.lyricsLoadsInProgress,
            crossfadeSeconds = appState.crossfadeSeconds,
            equalizerAvailable = equalizerAvailable,
            offlineOnly = appState.offlineOnly,
            downloadUsingCellular = appState.downloadUsingCellular,
            downloadedSizeBytes = appState.downloadedSizeBytes,
            cacheSizeBytes = appState.cacheSizeBytes,
            appUpdateController = appUpdateController,
            trackForPlaylistAdd = appState.trackForPlaylistAdd,
            playlistPickerPlaylists = appState.playlistPickerPlaylists,
            playlistPickerLoading = appState.playlistPickerLoading,
            playlistAddInProgress = appState.playlistAddInProgress,
            duplicatePlaylistForAdd = appState.duplicatePlaylistForAdd,
            artistChoices = appState.artistChoices,
        ),
        actions = TMusicAppRenderActions(
            onUseLocalBackendChange = onUseLocalBackendChange,
            onGoogleSignIn = onGoogleSignIn,
            onContinueOffline = onContinueOffline,
            onRetry = { loadLibrary(appState.destination) },
            onRefreshCurrentPlaylist = onRefreshCurrentPlaylist,
            onRefreshArtist = { artist ->
                loadArtistAlbums(artist, true)
                loadSimilarArtists(artist, true)
            },
            onRefreshAlbum = { album -> loadAlbumTracks(album, true) },
            onLoadMoreArtists = onLoadMoreArtists,
            onArtistSortChange = onArtistSortChange,
            onLoadMoreAlbums = onLoadMoreAlbums,
            onLoadMoreRecentAlbums = onLoadMoreRecentAlbums,
            onLoadMoreAlbumTracks = { album -> loadAlbumTracks(album, false) },
            onLoadMorePlaylistTracks = { playlist ->
                if (playlist.isFavoritesPlaylist()) {
                    loadFullFavoritesPlaylist(playlist)
                } else {
                    loadPlaylistTracks(playlist, false)
                }
            },
            onOfflineOnlyChange = onOfflineOnlyChange,
            onScrobblingPausedChange = onScrobblingPausedChange,
            onShowOnlyActiveSyncedLyricsChange = onShowOnlyActiveSyncedLyricsChange,
            onCenterSyncedLyricsChange = onCenterSyncedLyricsChange,
            onAnimatedPlayerBackgroundChange = onAnimatedPlayerBackgroundChange,
            onCrossfadeSecondsChange = onCrossfadeSecondsChange,
            onDownloadUsingCellularChange = onDownloadUsingCellularChange,
            onOpenEqualizer = onOpenEqualizer,
            onCreatePlaylist = onCreatePlaylist,
            onUpdatePlaylist = onUpdatePlaylist,
            onDeletePlaylist = onDeletePlaylist,
            onAddTrackToPlaylistClick = onAddTrackToPlaylistClick,
            onDownloadPlaylist = onDownloadPlaylist,
            onDeletePlaylistDownload = onDeletePlaylistDownload,
            onPlayPlaylist = onPlayPlaylist,
            onShufflePlayPlaylist = onShufflePlayPlaylist,
            onPlayPlaylistTrack = onPlayPlaylistTrack,
            onRemoveTrackFromPlaylist = onRemoveTrackFromPlaylist,
            onReorderPlaylistTracks = onReorderPlaylistTracks,
            onRequestArtwork = onRequestArtwork,
            onConnectLastFm = onConnectLastFm,
            onCompleteLastFmSession = onCompleteLastFmSession,
            onDisconnectLastFm = onDisconnectLastFm,
            onSyncLastFmUpdates = onSyncLastFmUpdates,
            onCreateWebLoginCode = onCreateWebLoginCode,
            onClearDownloads = onClearDownloads,
            onClearCache = onClearCache,
            onCheckUpdates = onCheckUpdates,
            onSelectTab = onSelectTab,
            onSelectPlaylist = onSelectPlaylist,
            onShowAllArtists = onShowAllArtists,
            onSelectArtist = onSelectArtist,
            onSelectAlbum = onSelectAlbum,
            onPlayAlbum = onPlayAlbum,
            onPlayAlbumTrack = onPlayAlbumTrack,
            onToggleAlbumInLibrary = onToggleAlbumInLibrary,
            onDownloadAlbum = onDownloadAlbum,
            onDeleteAlbumDownload = onDeleteAlbumDownload,
            onGoToAlbumArtist = onGoToAlbumArtist,
            onBack = onBack,
            onSelectTrack = onSelectTrack,
            onSearchQueryChange = {
                appState.searchQuery = it
                appState.searchTrackOffset = 0
                appState.searchHasMore = false
            },
            onLoadMoreSearchTracks = {
                if (!appState.searchLoading && appState.searchHasMore && appState.searchQuery.isNotBlank()) {
                    appState.searchTrackOffset = appState.searchResults.tracks.size
                }
            },
            onClearRecentItems = onClearRecentItems,
            onRecentItemClick = onRecentItemClick,
            onSelectSearchArtist = onSelectSearchArtist,
            onSelectSearchAlbum = onSelectSearchAlbum,
            onSelectSearchTrack = onSelectSearchTrack,
            onOpenFullPlayer = onOpenFullPlayer,
            onCloseFullPlayer = { appState.fullPlayerOpen = false },
            onOpenQueue = { appState.queueOpen = true },
            onCloseQueue = { appState.queueOpen = false },
            onSelectQueueTrack = onSelectQueueTrack,
            onRemoveQueueTrack = onRemoveQueueTrack,
            onReorderQueueTracks = onReorderQueueTracks,
            onAddCurrentTrackToPlaylist = { appState.playerState.currentTrack?.let(onAddTrackToPlaylistClick) },
            onAddTrackToQueue = onAddTrackToQueue,
            onGoToTrackArtist = onGoToTrackArtist,
            onGoToTrackAlbum = onGoToTrackAlbum,
            onToggleCurrentFavorite = { appState.playerState.currentTrack?.let(onToggleTrackFavorite) },
            onToggleTrackFavorite = onToggleTrackFavorite,
            onSkipPrevious = { onSkipInQueue(-1, true) },
            onSkipNext = { onSkipInQueue(1, true) },
            onSwipePreviousTrack = { onSkipInQueue(-1, false) },
            onShuffleChange = onShuffleChange,
            onRepeatModeChange = onRepeatModeChange,
            onTogglePlayback = onTogglePlayback,
            onSeek = onSeek,
            onRefreshCurrentLyrics = { appState.playerState.currentTrack?.let(onRefreshLyrics) },
            onSignOut = onSignOut,
            onDismissAddToPlaylist = {
                appState.trackForPlaylistAdd = null
                appState.duplicatePlaylistForAdd = null
            },
            onSelectPlaylistForTrack = onSelectPlaylistForTrack,
            onConfirmDuplicatePlaylist = onConfirmDuplicatePlaylist,
            onDismissDuplicatePlaylist = { appState.duplicatePlaylistForAdd = null },
            onDismissArtistChoices = { appState.artistChoices = emptyList() },
            onSelectArtistChoice = { artist ->
                appState.artistChoices = emptyList()
                onSelectArtist(artist)
            },
        ),
        showEnableCellularDownloadDialog = appState.showEnableCellularDownloadDialog,
        onDismissEnableCellularDownloadDialog = { appState.showEnableCellularDownloadDialog = false },
        onEnableCellularDownload = {
            appState.showEnableCellularDownloadDialog = false
            onDownloadUsingCellularChange(true)
        },
    )
}
