package dev.teacode.tmusic.ui

import dev.teacode.tmusic.data.AppCacheStore
import dev.teacode.tmusic.data.ArtworkCacheStore
import dev.teacode.tmusic.data.LibraryCacheStore
import dev.teacode.tmusic.data.OfflineLyricsStore
import dev.teacode.tmusic.data.PlaybackStateStore
import dev.teacode.tmusic.data.RemoteAuthRepository
import dev.teacode.tmusic.data.RemoteMusicRepository
import dev.teacode.tmusic.data.UserPreferencesStore
import dev.teacode.tmusic.domain.DownloadState
import dev.teacode.tmusic.domain.LibraryAlbum
import dev.teacode.tmusic.domain.Playlist
import dev.teacode.tmusic.domain.Track
import kotlinx.coroutines.CoroutineScope

internal fun createCollectionDownloadController(
    appState: TMusicAppMutableState,
    scope: CoroutineScope,
    musicRepository: RemoteMusicRepository,
    libraryCacheStore: LibraryCacheStore,
    userPreferencesStore: UserPreferencesStore,
    canUseNetworkForCollectionDownloads: () -> Boolean,
    playlistIsFullyDownloaded: (Playlist) -> Boolean,
    hasCachedArtwork: (String) -> Boolean,
    updateTrackDownloadState: (String, DownloadState) -> Unit,
    refreshStorageStats: () -> Unit,
    downloadPlaylist: (Playlist) -> Unit,
    downloadAlbum: (LibraryAlbum, List<Track>) -> Unit,
) = CollectionDownloadControlActionHost(
    scope = scope,
    musicRepository = musicRepository,
    libraryCacheStore = libraryCacheStore,
    userPreferencesStore = userPreferencesStore,
    getOfflineAlbumIds = { appState.offlineAlbumIds },
    setOfflineAlbumIds = { appState.offlineAlbumIds = it },
    getAlbums = { appState.albums },
    setAlbums = { appState.albums = it },
    getSavedAlbums = { appState.savedAlbums },
    setSavedAlbums = { appState.savedAlbums = it },
    getAlbumsByArtist = { appState.albumsByArtist },
    setAlbumsByArtist = { appState.albumsByArtist = it },
    getAppearsOnByArtist = { appState.appearsOnByArtist },
    setAppearsOnByArtist = { appState.appearsOnByArtist = it },
    getPlaylists = { appState.playlists },
    setPlaylists = { appState.playlists = it },
    getTracks = { appState.tracks },
    getAlbumTracksById = { appState.albumTracksById },
    getPlaylistDownloadJobs = { appState.playlistDownloadJobs },
    setPlaylistDownloadJobs = { appState.playlistDownloadJobs = it },
    getAlbumDownloadJobs = { appState.albumDownloadJobs },
    setAlbumDownloadJobs = { appState.albumDownloadJobs = it },
    setDownloadUsingCellularState = { appState.downloadUsingCellular = it },
    canUseNetworkForCollectionDownloads = canUseNetworkForCollectionDownloads,
    playlistIsFullyDownloaded = playlistIsFullyDownloaded,
    hasCachedArtwork = hasCachedArtwork,
    updateTrackDownloadState = updateTrackDownloadState,
    refreshStorageStats = refreshStorageStats,
    downloadPlaylist = downloadPlaylist,
    downloadAlbum = downloadAlbum,
)

internal fun createDownloadController(
    appState: TMusicAppMutableState,
    scope: CoroutineScope,
    musicRepository: RemoteMusicRepository,
    authRepository: RemoteAuthRepository,
    libraryCacheStore: LibraryCacheStore,
    canUseMediaServerRequests: () -> Boolean,
    mediaDisabledMessage: () -> String,
    updateTrackDownloadState: (String, DownloadState) -> Unit,
    ensureTrackDownloaded: suspend (Track) -> Unit,
    cacheDownloadedAssets: suspend (Track) -> Unit,
    hasCachedArtwork: (String) -> Boolean,
    disableMediaPlaybackForAccount: () -> Unit,
    refreshStorageStats: () -> Unit,
    pausePlaylistDownload: (Playlist) -> Unit,
    canUseNetworkForCollectionDownloads: () -> Boolean,
    applyPlaylistTrackPage: (Playlist, dev.teacode.tmusic.data.PlaylistPayload, Boolean) -> Playlist?,
    markServerUnavailable: (Throwable) -> Unit,
    requestEnableCellularDownloads: () -> Unit,
    pauseAlbumDownload: (LibraryAlbum, List<Track>) -> Unit,
    mergeLoadedTracks: (List<Track>) -> Unit,
    updateAlbumOfflineFlag: (String, Boolean) -> Unit,
) = DownloadActionHost(
    scope = scope,
    canUseMediaServerRequests = canUseMediaServerRequests,
    isOfflineOnly = { appState.offlineOnly },
    getSyncMode = { appState.syncMode },
    getAccount = { appState.account },
    musicRepository = musicRepository,
    authRepository = authRepository,
    libraryCacheStore = libraryCacheStore,
    getPlaylists = { appState.playlists },
    setPlaylists = { appState.playlists = it },
    getTracks = { appState.tracks },
    setTracks = { appState.tracks = it },
    getSavedAlbums = { appState.savedAlbums },
    setSavedAlbums = { appState.savedAlbums = it },
    mediaDisabledMessage = mediaDisabledMessage,
    updateTrackDownloadState = updateTrackDownloadState,
    ensureTrackDownloaded = ensureTrackDownloaded,
    cacheDownloadedAssets = cacheDownloadedAssets,
    hasCachedArtwork = hasCachedArtwork,
    disableMediaPlaybackForAccount = disableMediaPlaybackForAccount,
    setAccessToken = { appState.accessToken = it },
    setLibraryError = { appState.libraryError = it },
    refreshStorageStats = refreshStorageStats,
    getPlaylistDownloadJobs = { appState.playlistDownloadJobs },
    setPlaylistDownloadJobs = { appState.playlistDownloadJobs = it },
    pausePlaylistDownload = pausePlaylistDownload,
    canUseNetworkForCollectionDownloads = canUseNetworkForCollectionDownloads,
    applyPlaylistTrackPage = applyPlaylistTrackPage,
    markServerUnavailable = markServerUnavailable,
    requestEnableCellularDownloads = requestEnableCellularDownloads,
    getAlbumDownloadJobs = { appState.albumDownloadJobs },
    setAlbumDownloadJobs = { appState.albumDownloadJobs = it },
    pauseAlbumDownload = pauseAlbumDownload,
    getAlbums = { appState.albums },
    setAlbums = { appState.albums = it },
    getAlbumsByArtist = { appState.albumsByArtist },
    setAlbumsByArtist = { appState.albumsByArtist = it },
    getAppearsOnByArtist = { appState.appearsOnByArtist },
    setAppearsOnByArtist = { appState.appearsOnByArtist = it },
    getAlbumTracksById = { appState.albumTracksById },
    setAlbumTracksById = { appState.albumTracksById = it },
    mergeLoadedTracks = mergeLoadedTracks,
    updateAlbumOfflineFlag = updateAlbumOfflineFlag,
)

internal fun createStorageController(
    appState: TMusicAppMutableState,
    scope: CoroutineScope,
    userPreferencesStore: UserPreferencesStore,
    playbackStateStore: PlaybackStateStore,
    musicRepository: RemoteMusicRepository,
    offlineLyricsStore: OfflineLyricsStore,
    artworkCacheStore: ArtworkCacheStore,
    libraryCacheStore: LibraryCacheStore,
    appCacheStore: AppCacheStore,
    canUseServerRequests: () -> Boolean,
    getActivePlaybackCacheKey: () -> String?,
    clearGaplessPlaybackState: () -> Unit,
    refreshStorageStats: () -> Unit,
    updateTrackDownloadState: (String, DownloadState) -> Unit,
    clearPlaybackCache: () -> Unit,
    clearPlaybackCacheExcept: (Set<String>) -> Unit,
    playbackCacheDirName: String,
) = StorageMaintenanceActionHost(
    scope = scope,
    getAlbumDownloadJobs = { appState.albumDownloadJobs },
    setAlbumDownloadJobs = { appState.albumDownloadJobs = it },
    getPlaylistDownloadJobs = { appState.playlistDownloadJobs },
    setPlaylistDownloadJobs = { appState.playlistDownloadJobs = it },
    getPlayerState = { appState.playerState },
    getActivePlaybackCacheKey = getActivePlaybackCacheKey,
    setPlayerState = { appState.playerState = it },
    getPlaylists = { appState.playlists },
    setPlaylists = { appState.playlists = it },
    getTracks = { appState.tracks },
    setTracks = { appState.tracks = it },
    getAlbums = { appState.albums },
    setAlbums = { appState.albums = it },
    getSavedAlbums = { appState.savedAlbums },
    setSavedAlbums = { appState.savedAlbums = it },
    getAlbumsByArtist = { appState.albumsByArtist },
    setAlbumsByArtist = { appState.albumsByArtist = it },
    getAppearsOnByArtist = { appState.appearsOnByArtist },
    setAppearsOnByArtist = { appState.appearsOnByArtist = it },
    setOfflineAlbumIds = { appState.offlineAlbumIds = it },
    userPreferencesStore = userPreferencesStore,
    getPlaybackQueue = { appState.playbackQueue },
    setPlaybackQueue = { appState.playbackQueue = it },
    clearGaplessPlaybackState = clearGaplessPlaybackState,
    setPrefetchedPlaybackUrls = { appState.prefetchedPlaybackUrls = it },
    setPlaybackUrlPrefetchesInProgress = { appState.playbackUrlPrefetchesInProgress = it },
    playbackStateStore = playbackStateStore,
    canUseServerRequests = canUseServerRequests,
    setArtists = { appState.artists = it },
    getArtworkBitmaps = { appState.artworkBitmaps },
    setArtworkBitmaps = appState::replaceArtworkBitmaps,
    getLyricsByTrackId = { appState.lyricsByTrackId },
    setLyricsByTrackId = { appState.lyricsByTrackId = it },
    musicRepository = musicRepository,
    offlineLyricsStore = offlineLyricsStore,
    artworkCacheStore = artworkCacheStore,
    libraryCacheStore = libraryCacheStore,
    setLibraryNotice = { appState.libraryNotice = it },
    setLibraryError = { appState.libraryError = it },
    refreshStorageStats = refreshStorageStats,
    setArtworkLoadsInProgress = { appState.artworkLoadsInProgress = it },
    setProfileAvatarBitmap = { appState.profileAvatarBitmap = it },
    setProfileAvatarLoadKey = { appState.profileAvatarLoadKey = it },
    appCacheStore = appCacheStore,
    updateTrackDownloadState = updateTrackDownloadState,
    clearPlaybackCache = clearPlaybackCache,
    clearPlaybackCacheExcept = clearPlaybackCacheExcept,
    playbackCacheDirName = playbackCacheDirName,
)
