package dev.teacode.tmusic.ui

import androidx.media3.exoplayer.ExoPlayer
import dev.teacode.tmusic.data.RemoteAuthRepository
import dev.teacode.tmusic.data.RemoteMusicRepository
import dev.teacode.tmusic.data.UserPreferencesStore
import dev.teacode.tmusic.domain.Track
import kotlinx.coroutines.CoroutineScope

internal fun createPlaybackRuntimeController(
    appState: TMusicAppMutableState,
    scope: CoroutineScope,
    getExoPlayer: () -> ExoPlayer,
    setExoPlayer: (ExoPlayer) -> Unit,
    musicRepository: RemoteMusicRepository,
    authRepository: RemoteAuthRepository,
    completeActivePlayEvent: (Boolean) -> Unit,
    ensureActivePlayEvent: (Track, Boolean) -> Unit,
    clearNowPlayingEvent: (ActivePlayEvent?) -> Unit,
    clearGaplessPlaybackState: () -> Unit,
    cancelCrossfade: () -> Unit,
    canUseMediaServerRequests: () -> Boolean,
    loadArtwork: (String, ArtworkImageSize) -> Unit,
    loadLyrics: (Track) -> Unit,
    playQueuedTrack: (Track, PlaybackQueue, Long, Boolean) -> Unit,
) = PlaybackRuntimeActionHost(
    scope = scope,
    getExoPlayer = getExoPlayer,
    setExoPlayer = setExoPlayer,
    musicRepository = musicRepository,
    authRepository = authRepository,
    getAccount = { appState.account },
    getRepeatMode = { appState.repeatMode },
    getCrossfadeSeconds = { appState.crossfadeSeconds },
    getCrossfadeJob = { appState.crossfadeJob },
    setCrossfadeJob = { appState.crossfadeJob = it },
    getPreparedCrossfade = { appState.preparedCrossfade },
    setPreparedCrossfade = { appState.preparedCrossfade = it },
    getPlaybackQueueGeneration = { appState.playbackQueueGeneration },
    getPlaybackQueue = { appState.playbackQueue },
    setPlaybackQueue = { appState.playbackQueue = it },
    getPlayerState = { appState.playerState },
    setPlayerState = { appState.playerState = it },
    getActivePlayEvent = { appState.activePlayEventState.value },
    completeActivePlayEvent = completeActivePlayEvent,
    ensureActivePlayEvent = ensureActivePlayEvent,
    clearNowPlayingEvent = clearNowPlayingEvent,
    clearGaplessPlaybackState = clearGaplessPlaybackState,
    cancelCrossfade = cancelCrossfade,
    getGaplessPlaybackRequest = { appState.gaplessPlaybackRequest },
    setGaplessPlaybackRequest = { appState.gaplessPlaybackRequest = it },
    getGaplessMediaQueueIndices = { appState.gaplessMediaQueueIndices },
    setGaplessMediaQueueIndices = { appState.gaplessMediaQueueIndices = it },
    getGaplessMediaUrls = { appState.gaplessMediaUrls },
    setGaplessMediaUrls = { appState.gaplessMediaUrls = it },
    getPrefetchedPlaybackUrls = { appState.prefetchedPlaybackUrls },
    setPrefetchedPlaybackUrls = { appState.prefetchedPlaybackUrls = it },
    getPlaybackUrlPrefetchesInProgress = { appState.playbackUrlPrefetchesInProgress },
    setPlaybackUrlPrefetchesInProgress = { appState.playbackUrlPrefetchesInProgress = it },
    canUseMediaServerRequests = canUseMediaServerRequests,
    setAccessToken = { appState.accessToken = it },
    setPlaybackBufferedFraction = { appState.playbackBufferedFraction = it },
    incrementPlaybackStartSerial = { appState.playbackStartSerial += 1 },
    incrementRequestedNextPrefetch = { appState.requestedNextPrefetch += 1 },
    incrementCrossfadePreparationSerial = { appState.crossfadePreparationSerial += 1 },
    setPendingTransitionArtworkTrackId = { appState.pendingTransitionArtworkTrackId = it },
    loadArtwork = loadArtwork,
    loadLyrics = loadLyrics,
    playQueuedTrack = playQueuedTrack,
)

internal fun createPlayQueuedTrackController(
    appState: TMusicAppMutableState,
    scope: CoroutineScope,
    exoPlayer: ExoPlayer,
    musicRepository: RemoteMusicRepository,
    authRepository: RemoteAuthRepository,
    cancelCrossfade: () -> Unit,
    canUseMediaServerRequests: () -> Boolean,
    disableMediaPlaybackForAccount: () -> Unit,
    mediaDisabledMessage: () -> String,
    clearGaplessPlaybackState: () -> Unit,
    localOrCachedPlaybackUrl: (Track) -> String?,
    loadArtwork: (String, ArtworkImageSize) -> Unit,
    prefetchNextTrackUrl: (PlaybackQueue) -> Unit,
    startGaplessPlayback: (Track, PlaybackQueue, List<String>, Long) -> Unit,
    startPlayback: (Track, String, Long) -> Unit,
    markServerUnavailable: (Throwable) -> Unit,
) = PlayQueuedTrackActionHost(
    scope = scope,
    exoPlayer = exoPlayer,
    musicRepository = musicRepository,
    authRepository = authRepository,
    getAccount = { appState.account },
    getShuffleEnabled = { appState.shuffleEnabled },
    getPlaybackQueueGeneration = { appState.playbackQueueGeneration },
    setPlaybackQueueGeneration = { appState.playbackQueueGeneration = it },
    getPlaybackQueue = { appState.playbackQueue },
    setPlaybackQueue = { appState.playbackQueue = it },
    getPlayerState = { appState.playerState },
    setPlayerState = { appState.playerState = it },
    setPlaybackBufferedFraction = { appState.playbackBufferedFraction = it },
    getPrefetchedPlaybackUrls = { appState.prefetchedPlaybackUrls },
    setPrefetchedPlaybackUrls = { appState.prefetchedPlaybackUrls = it },
    getOfflineOnly = { appState.offlineOnly },
    getSyncMode = { appState.syncMode },
    currentStreamRequestSerial = { appState.streamRequestSerial },
    nextStreamRequestSerial = {
        appState.streamRequestSerial += 1
        appState.streamRequestSerial
    },
    cancelCrossfade = cancelCrossfade,
    canUseMediaServerRequests = canUseMediaServerRequests,
    disableMediaPlaybackForAccount = disableMediaPlaybackForAccount,
    mediaDisabledMessage = mediaDisabledMessage,
    clearGaplessPlaybackState = clearGaplessPlaybackState,
    localOrCachedPlaybackUrl = localOrCachedPlaybackUrl,
    loadArtwork = loadArtwork,
    prefetchNextTrackUrl = prefetchNextTrackUrl,
    startGaplessPlayback = startGaplessPlayback,
    startPlayback = startPlayback,
    setAccessToken = { appState.accessToken = it },
    markServerUnavailable = markServerUnavailable,
    setLibraryNotice = { appState.libraryNotice = it },
    setPlayerError = { appState.playerError = it },
)

internal fun createPlaybackErrorController(
    appState: TMusicAppMutableState,
    scope: CoroutineScope,
    exoPlayer: ExoPlayer,
    musicRepository: RemoteMusicRepository,
    authRepository: RemoteAuthRepository,
    clearGaplessPlaybackState: () -> Unit,
    cancelCrossfade: () -> Unit,
    canUseMediaServerRequests: () -> Boolean,
    mediaDisabledMessage: () -> String,
    disableMediaPlaybackForAccount: () -> Unit,
    markServerUnavailable: (Throwable) -> Unit,
) = PlaybackErrorActionHost(
    scope = scope,
    exoPlayer = exoPlayer,
    musicRepository = musicRepository,
    authRepository = authRepository,
    getPlayerState = { appState.playerState },
    setPlayerState = { appState.playerState = it },
    getPlaybackQueue = { appState.playbackQueue },
    getAccount = { appState.account },
    getPrefetchedPlaybackUrls = { appState.prefetchedPlaybackUrls },
    setPrefetchedPlaybackUrls = { appState.prefetchedPlaybackUrls = it },
    getPlaybackUrlPrefetchesInProgress = { appState.playbackUrlPrefetchesInProgress },
    setPlaybackUrlPrefetchesInProgress = { appState.playbackUrlPrefetchesInProgress = it },
    incrementStreamRequestSerial = {
        appState.streamRequestSerial += 1
        appState.streamRequestSerial
    },
    getStreamRequestSerial = { appState.streamRequestSerial },
    clearGaplessPlaybackState = clearGaplessPlaybackState,
    cancelCrossfade = cancelCrossfade,
    canUseMediaServerRequests = canUseMediaServerRequests,
    mediaDisabledMessage = mediaDisabledMessage,
    setAccessToken = { appState.accessToken = it },
    setPlaybackBufferedFraction = { appState.playbackBufferedFraction = it },
    incrementPlaybackStartSerial = { appState.playbackStartSerial += 1 },
    incrementRequestedNextPrefetch = { appState.requestedNextPrefetch += 1 },
    disableMediaPlaybackForAccount = disableMediaPlaybackForAccount,
    markServerUnavailable = markServerUnavailable,
    setPlayerError = { appState.playerError = it },
)

internal fun createPlaybackQueueControlController(
    appState: TMusicAppMutableState,
    exoPlayer: ExoPlayer,
    userPreferencesStore: UserPreferencesStore,
    cancelCrossfade: () -> Unit,
    clearGaplessPlaybackState: () -> Unit,
    removePreparedPlaybackItemsAfterCurrent: () -> Unit,
    clearNowPlayingEvent: (ActivePlayEvent?) -> Unit,
    canUseMediaServerRequests: () -> Boolean,
    localOrCachedPlaybackUrl: (Track) -> String?,
    completeActivePlayEvent: (Boolean) -> Unit,
    ensureActivePlayEvent: (Track, Boolean) -> Unit,
    seekPreparedQueueMediaItem: (Int, Int) -> Boolean,
    playQueuedTrack: (Track, PlaybackQueue, Int?, Int) -> Unit,
    mergeLoadedTracks: (List<Track>) -> Unit,
    loadArtwork: (String, ArtworkImageSize) -> Unit,
    applyPlaybackQueueOrderWithoutInterrupt: (PlaybackQueue) -> Unit,
) = PlaybackQueueControlActionHost(
    exoPlayer = exoPlayer,
    userPreferencesStore = userPreferencesStore,
    getPlaybackQueue = { appState.playbackQueue },
    setPlaybackQueue = { appState.playbackQueue = it },
    getPlayerState = { appState.playerState },
    setPlayerState = { appState.playerState = it },
    getActivePlayEvent = { appState.activePlayEventState.value },
    setActivePlayEvent = { appState.activePlayEventState.value = it },
    getQueueInsertionAnchorTrackId = { appState.queueInsertionAnchorTrackId },
    setQueueInsertionAnchorTrackId = { appState.queueInsertionAnchorTrackId = it },
    getQueueInsertionCursor = { appState.queueInsertionCursor },
    setQueueInsertionCursor = { appState.queueInsertionCursor = it },
    getShuffleEnabled = { appState.shuffleEnabled },
    setShuffleEnabledState = { appState.shuffleEnabled = it },
    setRepeatModeState = { appState.repeatMode = it },
    cancelCrossfade = cancelCrossfade,
    clearGaplessPlaybackState = clearGaplessPlaybackState,
    removePreparedPlaybackItemsAfterCurrent = removePreparedPlaybackItemsAfterCurrent,
    clearNowPlayingEvent = clearNowPlayingEvent,
    canUseMediaServerRequests = canUseMediaServerRequests,
    localOrCachedPlaybackUrl = localOrCachedPlaybackUrl,
    completeActivePlayEvent = completeActivePlayEvent,
    ensureActivePlayEvent = ensureActivePlayEvent,
    seekPreparedQueueMediaItem = seekPreparedQueueMediaItem,
    playQueuedTrack = playQueuedTrack,
    mergeLoadedTracks = mergeLoadedTracks,
    loadArtwork = loadArtwork,
    incrementRequestedNextPrefetch = { appState.requestedNextPrefetch += 1 },
    applyPlaybackQueueOrderWithoutInterrupt = applyPlaybackQueueOrderWithoutInterrupt,
    setLibraryNotice = { appState.libraryNotice = it },
)
